### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by suneesh-anand** [rytilahti/python-yeelightbt#14]
pi@raspberrypi:~/.local/bin $ python yeelightbt
Traceback (most recent call last):
  File "yeelightbt", line 11, in <module>
    load_entry_point('python-yeelightbt==0.0.2', 'console_scripts', 'yeelightbt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/.local/lib/python2.7/site-packages/yeelightbt/__init__.py", line 2, in <module>
    from .lamp import Lamp
  File "/home/pi/.local/lib/python2.7/site-packages/yeelightbt/lamp.py", line 5, in <module>
    from .structures import Request, Response
  File "/home/pi/.local/lib/python2.7/site-packages/yeelightbt/structures.py", line 70, in <module>
    "unknown" / Const(Byte, 0x00)
  File "/home/pi/.local/lib/python2.7/site-packages/construct/core.py", line 2440, in __init__
    super(Const, self).__init__(subcon)
  File "/home/pi/.local/lib/python2.7/site-packages/construct/core.py", line 549, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

**Comment by rytilahti** [comment]
Fixed in 0.0.3 / master branch, please update.
