### ISSUE TITLE
trace 

### ISSUE THREAD

**Issue by deennoo** [rytilahti/python-yeelightbt#2]
Hello,

Just try your lib and follow your readme, before adding to home assistant, want to try alone.

Just build your lib with

[code] python3 setup.py install [code/]

and try : 
[code]yeelightbt --help[code/]

and get this error

[code]Traceback (most recent call last):
  File "/usr/local/bin/yeelightbt", line 9, in <module>
    load_entry_point('python-yeelightbt==0.0.1', 'console_scripts', 'yeelightbt')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named 'main'
[code/]

can you help please ?

**Comment by rytilahti** [comment]
Sorry about that, it was my mistake and I just commited a fix for it.
