### ISSUE TITLE
ImportError: No module named main

### ISSUE THREAD

**Issue by jenccnej** [rytilahti/python-yeelightbt#3]
Hi

I'm trying to run this lib on Raspberry Pi 3, but getting an error message:

`Traceback (most recent call last):
  File "/usr/local/bin/yeelightbt", line 9, in <module>
    load_entry_point('python-yeelightbt==0.0.1', 'console_scripts', 'yeelightbt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named main`

What am I doing wrong?

**Comment by rytilahti** [comment]
It was an error on my side, should be fixed now!
