### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by walwal99** [rytilahti/python-yeelightbt#31]
pi@hassbian:/srv/homeassistant/bin $ ./yeelightbt
INFO:yeelightbt.connection:Requesting characteristics for uuid 8f65073d-9f57-4aaa-afea-397d19d5bbeb
INFO:yeelightbt.connection:Requesting characteristics for uuid aa7d3f34-2d4f-41e0-807f-52fbf8cf7443
Got notif: <Lamp f8:24:41:ea:70:f0 is_on(False) mode(White) rgb((0, 0, 0, 0)) brightness(71) colortemp(3700)>
ERROR:yeelightbt.lamp:got exception on {'type': 'GetState', 'payload': {}}, tries left 3: Device disconnected
Traceback (most recent call last):
  File "./yeelightbt", line 11, in <module>
    load_entry_point('python-yeelightbt==0.0.4', 'console_scripts', 'yeelightbt')()
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/yeelightbt/cli.py", line 61, in cli
    lamp.state()
  File "/srv/homeassistant/lib/python3.5/site-packages/yeelightbt/lamp.py", line 36, in _wrap
    self._conn.wait(wait)
  File "/srv/homeassistant/lib/python3.5/site-packages/yeelightbt/connection.py", line 74, in wait
    self._conn.waitForNotifications(timeout=0.1)
  File "/srv/homeassistant/lib/python3.5/site-packages/bluepy/btle.py", line 560, in waitForNotifications
    resp = self._getResp(['ntfy','ind'], timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected

and

on HA , when I Turn on light switch

there is messages "Failed to call service light/turn_on. Helper not started (did you call connect()"

Would you tell me some solutions?

yeelighbt scan working well

**Comment by rytilahti** [comment]
Sorry for that, I think I should remove the homeassistant "component" completely, as it never was finished nor intended for real use with all the troubles with bluetooth devices & homeassistant. PRs to fix the issues are welcome, but this library is not actively maintained.
