### ISSUE TITLE
yeelightbt not working on rpi

### ISSUE THREAD

**Issue by svennd** [rytilahti/python-yeelightbt#36]
I installed your library as suggested :
`pip3 install git+https://github.com/rytilahti/python-yeelightbt/`

Sadly when trying anything I get this error : (python 3.7) Any idea where I should look ? 

```Traceback (most recent call last):
  File "/usr/local/bin/yeelightbt", line 6, in <module>
    from yeelightbt.cli import cli
  File "/usr/local/lib/python3.7/dist-packages/yeelightbt/__init__.py", line 2, in <module>
    from .lamp import Lamp
  File "/usr/local/lib/python3.7/dist-packages/yeelightbt/lamp.py", line 7, in <module>
    from .structures import Request, Response, StateResult
  File "/usr/local/lib/python3.7/dist-packages/yeelightbt/structures.py", line 4, in <module>
    from construct import (
ImportError: cannot import name 'Embedded' from 'construct' (/usr/local/lib/python3.7/dist-packages/construct/__init__.py)
```

thanks !

**Comment by svennd** [comment]
I found the issue; Seems Embedded is [dropped ](https://construct.readthedocs.io/en/latest/transition210.html)from the construct library; A workaround could be downgrading : 
`pip3 install construct==2.9.52`
