### ISSUE TITLE
yeelightbt with Candela on rasp 4 homeassistant dont work

### ISSUE THREAD

**Issue by Titanius** [rytilahti/python-yeelightbt#37]
/config/configuration.yaml

light:
  - platform: yeelight_bt
    devices:
      Bedside:
        mac: F8:24:41:C0:AC:6V

/config/custom_components/yeelight_bt/

Logger: homeassistant.components.light
Source: custom_components/yeelight_bt/light.py:131 
Integration: Licht (documentation, issues) 
First occurred: 16:41:44 (1 occurrences) 
Last logged: 16:41:44

yeelight_bt: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/yeelight_bt/light.py", line 163, in update
    with self._dev:
  File "/config/custom_components/yeelight_bt/light.py", line 131, in _dev
    from yeelightbt import Lamp
ModuleNotFoundError: No module named 'yeelightbt'

**Comment by rytilahti** [comment]
You need to install the package also, I just added it as a requirement for the custom component (https://github.com/rytilahti/python-yeelightbt/commit/918ef56d5b08de880d12d1a82ccfcbad658325b0), so that should be done now automatically.

To install it manually, simply use pip:
```
pip install python-yeelightbt
```
