### ISSUE TITLE
homeassistant Unable to load plug-in

### ISSUE THREAD

**Issue by Guoer-xz** [rytilahti/python-yeelightbt#9]
I have installed the latest ha plugin to the specified directory, BlueZ has been fully installed, prompted to start as follows, how can I let it run up, thanks

#######################################################################
INFO:homeassistant.loader:Loaded light.yeelight_bt from custom_components.light.yeelight_bt
INFO:homeassistant.bootstrap:Setting up light
INFO:homeassistant.components.light:Setting up light.yeelight_bt
ERROR:homeassistant.components.light:Error while setting up platform yeelight_bt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 151, in _async_setup_platform
    entity_platform.add_entities, discovery_info
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/guoer/.homeassistant/custom_components/light/yeelight_bt.py", line 60, in setup_platform
    add_devices_callback(lights, True)  # request an update before adding
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 300, in add_entities
    entity.update()
  File "/Users/guoer/.homeassistant/custom_components/light/yeelight_bt.py", line 163, in update
    with self._dev:
  File "/Users/guoer/.homeassistant/custom_components/light/yeelight_bt.py", line 131, in _dev
    from yeelightbt import Lamp
ImportError: No module named 'yeelightbt'

**Comment by rytilahti** [comment]
It looks like you haven't installed the module itself, just the plugin. But as you are running on OSX, it won't work anyway as OSX has no Bluez, so I'm closing this.
